<?php
$title = 'Delete a post';
$this->headTitle($title);
?>

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span2"></div>
        <div class="span9">

            <form class="form-horizontal" action="<?=
            $this->url('post', array(
                'action' => 'deletepost',
                'id'     => $this->id,
            )) ?>" method="post">

                <fieldset>
                    <legend>Delete a Post</legend>

                    <div class="control-group">
                        <label class="control-label"></label>

                        <div class="controls">
                            <p>Are you sure that you want to delete [ <?= $post->guest_name ?> ]'s post?</p>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label"></label>

                        <div class="controls">
                            <button type="submit" name="del" value="Yes" class="btn btn-danger">YES</button>
                            <button type="submit" name="del" value="No" class="btn btn-inverse">NO</button>
                        </div>
                    </div>

                </fieldset>

            </form>
        </div>
    </div>
</div>